builds:
- 
  id: crawler
  binary: crawler
  main: ./main.go
  ldflags:
    - -s -w -X github.com/developer-overheid-nl/don-crawler/internal.VERSION={{.Version}} -X github.com/developer-overheid-nl/don-crawler/internal.BuildTime={{.Date}}
  env:
  - CGO_ENABLED=0
archives:
- 
  builds:
    - crawler
  wrap_in_directory: false
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: 32-bit
    amd64: 64-bit
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
